- name: Install Kubernetes components
  hosts: all
  become: yes
  tasks:
    - name: Add Kubernetes GPG key
      get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/rpm/repodata/repomd.xml.key
        dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
        mode: '0644'

    - name: Add Kubernetes APT repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes main"
        filename: kubernetes
        state: present

    - name: Install kubelet, kubeadm, and kubectl
      apt:
        name: ['kubelet', 'kubeadm', 'kubectl']
        update_cache: yes

    - name: Hold Kubernetes packages
      apt:
        name: "{{ item }}"
        state: present
        mark: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
