- name: Initialize Kubernetes master
  hosts: masters
  become: yes
  tasks:
    - name: Initialize master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16
      register: kubeadm_output
      changed_when: "'already initialized' not in kubeadm_output.stdout"

    - name: Save join command
      shell: |
        kubeadm token create --print-join-command
      register: join_command
      changed_when: false

    - name: Copy join command to file
      copy:
        content: "{{ join_command.stdout }}"
        dest: /tmp/join_command.sh
        mode: '0755'

    - name: Set up kubeconfig for user
      become_user: ubuntu
      shell: |
        mkdir -p $HOME/.kube
        sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        sudo chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Install Flannel network plugin
      become_user: ubuntu
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
