- name: Join worker to cluster
  hosts: workers
  become: yes
  tasks:
    - name: Copy join command from master
      fetch:
        src: /tmp/join_command.sh
        dest: /tmp/join_command.sh
        flat: yes

    - name: Join the worker node to cluster
      command: bash /tmp/join_command.sh
