- name: Deploy HA Argo CD on Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    argocd_namespace: argocd
    nodeport_http: 30080
    nodeport_https: 30443
    ha_manifest_url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/ha/install.yaml
    replicas: 3
    kubeconfig_path: /root/.kube/config
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

  tasks:

    - name: Delete all resources in Argo CD namespace
      ansible.builtin.shell: |
        kubectl delete all --all -n argocd

    - name: Delete configmaps, secrets, and other non-core resources in Argo CD namespace
      ansible.builtin.shell: |
        kubectl delete cm,secrets,svcaccount,role,rolebinding,networkpolicy --all -n argocd || true

    - name: Delete Argo CD namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: argocd
        state: absent

    - name: Wait for Argo CD namespace to terminate
      kubernetes.core.k8s_info:
        kind: Namespace
        name: argocd
      register: ns_status
      retries: 20
      delay: 5
      until: ns_status.resources | length == 0

    - name: Ensure python3-pip is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Ensure Kubernetes Python client is installed via apt
      ansible.builtin.apt:
        name: python3-kubernetes
        state: present

    - name: Create Argo CD namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: "{{ argocd_namespace }}"
        state: present

    - name: Apply HA Argo CD manifests
      ansible.builtin.command:
        cmd: kubectl apply -n "{{ argocd_namespace }}" -f "{{ ha_manifest_url }}"
      register: apply_result
      changed_when: "'configured' in apply_result.stdout or 'created' in apply_result.stdout"

    - name: Wait for each Argo CD resource to appear
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: "{{ item.kind }}"
        name: "{{ item.name }}"
        namespace: "{{ argocd_namespace }}"
      register: k8s_resource
      until: k8s_resource.resources | length > 0
      retries: 50
      delay: 6
      loop:
        - { name: argocd-server, kind: Deployment }
        - { name: argocd-repo-server, kind: Deployment }
        - { name: argocd-application-controller, kind: StatefulSet }
      loop_control:
        label: "{{ item.name }}"

    - name: Patch Argo CD components for HA
      kubernetes.core.k8s:
        namespace: "{{ argocd_namespace }}"
        name: "{{ item.name }}"
        kind: "{{ item.kind }}"
        merge_type: strategic-merge
        resource_definition:
          spec:
            replicas: "{{ replicas }}"
      loop:
        - { name: argocd-server, kind: Deployment }
        - { name: argocd-repo-server, kind: Deployment }
        - { name: argocd-application-controller, kind: StatefulSet }
      loop_control:
        label: "{{ item.name }}"

    - name: Get all Argo CD pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ argocd_namespace }}"
      register: argocd_pods_all

    - name: Set expected_count dynamically (as integer)
      set_fact:
        expected_count: "{{ argocd_pods_all.resources | length }}"

    - name: Wait until all Argo CD pods are Running
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ argocd_namespace }}"
      register: argocd_pods
      retries: 50
      delay: 5
      until: >
        (argocd_pods.resources | default([]) | selectattr('status.phase', 'equalto', 'Running') | list | length) >= (expected_count | int)
    
    - name: Fallback pause in case Argo CD not fully ready (optional but safe)
      ansible.builtin.pause:
        seconds: 60

    - name: Expose Argo CD server via NodePort
      kubernetes.core.k8s:
        namespace: "{{ argocd_namespace }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: argocd-server-nodeport
            labels:
              app: argocd-server
          spec:
            type: NodePort
            ports:
              - name: http
                port: 80
                targetPort: 8080
                nodePort: "{{ nodeport_http }}"
              - name: https
                port: 443
                targetPort: 8080
                nodePort: "{{ nodeport_https }}"
            selector:
              app.kubernetes.io/name: argocd-server
              app.kubernetes.io/part-of: argocd

    - name: Get Argo CD admin password
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: "{{ argocd_namespace }}"
        name: argocd-initial-admin-secret
      register: admin_secret

    - name: Output Argo CD access info
      debug:
        msg: |
          ✅ Argo CD (HA) is deployed successfully!
          🔗 Access URL: https://<ANY-NODE-IP>:{{ nodeport_https }}
          👤 Username: admin
          🔑 Password: {{ admin_secret.resources[0].data.password | b64decode }}