- name: Register SSH Git repository with Argo CD
  hosts: localhost
  become: true
  gather_facts: false

  vars:
    ssh_key_path: /tmp/argocd_git_ssh_key
    ssh_key_pub_path: /tmp/argocd_git_ssh_key.pub

  tasks:
    - name: Generate SSH key pair for Argo CD (if not exists)
      command: ssh-keygen -t rsa -b 4096 -C "argocd@local" -f {{ ssh_key_path }} -N ""
      args:
        creates: "{{ ssh_key_path }}"

    - name: Read private key
      slurp:
        src: "{{ ssh_key_path }}"
      register: slurped_ssh_key

    - name: Decode private key to string
      set_fact:
        ssh_private_key: "{{ slurped_ssh_key['content'] | b64decode }}"

    - name: Render secret manifest from template
      template:
        src: templates/argocd-ssh-secret.yaml.j2
        dest: /tmp/argocd-ssh-repo-secret.yaml

    - name: Apply Argo CD Git SSH repo secret
      command: kubectl apply -f /tmp/argocd-ssh-repo-secret.yaml

    - name: Show public key to add as GitHub Deploy Key
      debug:
        msg: "{{ lookup('file', ssh_key_pub_path) }}"