- name: Destroy Kubernetes Cluster Completely and Safely
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Unhold kubelet, kubeadm, kubectl if held
      shell: apt-mark unhold kubelet kubeadm kubectl
      register: unhold_result
      changed_when: "'were not held' not in unhold_result.stdout"
      ignore_errors: true

    - name: Remove Kubernetes components (kubeadm, kubelet, kubectl)
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: absent
        purge: true
        allow_change_held_packages: true

    - name: Reset kubeadm if installed
      ansible.builtin.stat:
        path: /usr/bin/kubeadm
      register: kubeadm_bin

    - name: Run kubeadm reset
      command: kubeadm reset -f
      when: kubeadm_bin.stat.exists
      ignore_errors: true

    - name: Stop kubelet service if present
      ansible.builtin.systemd:
        name: kubelet
        state: stopped
        enabled: false
      when: "'kubelet' in ansible_facts.services"
      ignore_errors: true

    - name: Stop docker service if present
      ansible.builtin.systemd:
        name: docker
        state: stopped
        enabled: false
      when: "'docker' in ansible_facts.services"
      ignore_errors: true

    - name: Flush iptables
      command: iptables -F
      ignore_errors: true

    - name: Remove Kubernetes and Docker directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes
        - /var/lib/etcd
        - /var/lib/kubelet
        - /etc/cni
        - /opt/cni
        - /var/run/kubernetes
        - /root/.kube
        - /home/dev/.kube
        - /var/lib/docker
        - /etc/docker
      ignore_errors: true

    - name: Remove Docker packages (if any)
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent
        purge: true
      ignore_errors: true

    - name: Autoremove and clean apt cache
      ansible.builtin.apt:
        autoremove: true
        purge: true
        clean: true

    - name: Reboot the node if enabled
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: reboot_after_cleanup | default(false)