- name: Install and configure HAProxy on master1
  hosts: haproxy_master
  become: yes
  tasks:

    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configure HAProxy for Kubernetes API
      template:
        src: /home/dev/kubernetestes/k8s-ansible/playbooks/templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
        backup: yes
      vars:
        master_nodes: "{{ groups['masters'] }}"
      notify:
        - Restart HAProxy

    - name: Enable and start HAProxy
      systemd:
        name: haproxy
        enabled: yes
        state: started

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted