- name: Install HAProxy and Keepalived on Master Nodes
  hosts: haproxy_master
  become: yes
  vars:
    vip_address: "{{ hostvars['localhost']['vip_address'] }}"
    haproxy_bind_port: "{{ hostvars['localhost']['haproxy_bind_port'] }}"
  tasks:

    - name: Install HAProxy and Keepalived
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - haproxy
        - keepalived

    - name: Configure HAProxy
      template:
        src: kubernetestes/k8s-ansible/playbooks/templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        mode: '0644'
        backup: yes
      notify:
        - Restart HAProxy

    - name: Configure Keepalived
      template:
        src: kubernetestes/k8s-ansible/playbooks/templates/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        mode: '0644'
        backup: yes
      notify:
        - Restart Keepalived

    - name: Enable and start HAProxy and Keepalived
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - haproxy
        - keepalived

  handlers:
    - name: Restart HAProxy
      systemd:
        name: haproxy
        state: restarted

    - name: Restart Keepalived
      systemd:
        name: keepalived
        state: restarted